# Generated by Django 2.2.28 on 2022-10-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="Himanshutest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.BigIntegerField()),
            ],
        ),
    ]
