# Generated by Django 2.2.28 on 2022-10-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_addeddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='himanshutest',
            name='test',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
