# Generated by Django 2.2.28 on 2022-10-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_himanshutest_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addeddata',
        ),
    ]
