# Generated by Django 2.2.28 on 2022-10-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_addeddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Himanshutest',
        ),
    ]
