# Generated by Django 2.2.28 on 2022-10-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_delete_himanshutest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
