# Generated by Django 2.2.28 on 2022-11-17 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_aaabbb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usertest',
        ),
    ]
